language: "en_core_web_md"

pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_featurizer_spacy"
- name: "ner_crf"
- name: "intent_classifier_sklearn"
- name: "rasa_composite_entities.CompositeEntityExtractor"

data: {
  "rasa_nlu_data": {
    "composite_entities": [
      {
        "name": "product_with_attributes",
        "patterns": [
            "@color @product with @pattern",
            "@pattern @color @product"
        ]
      }
    ],
    "common_examples": [
      {
        "text": "hey",
        "intent": "greet",
        "entities": []
      },
      {
        "text": "howdy",
        "intent": "greet",
        "entities": []
      },
      {
        "text": "hey there",
        "intent": "greet",
        "entities": []
      },
      {
        "text": "hello",
        "intent": "greet",
        "entities": []
      },
      {
        "text": "hi",
        "intent": "greet",
        "entities": []
      },
      {
        "text": "good morning",
        "intent": "greet",
        "entities": []
      },
      {
        "text": "good evening",
        "intent": "greet",
        "entities": []
      },
      {
        "text": "dear sir",
        "intent": "greet",
        "entities": []
      },
      {
        "text": "i am looking for a red shirt with stripes and checkered blue shoes.",
        "intent": "product_search",
        "entities" : [
          {
            "start": 19,
            "end": 22,
            "value": "red",
            "entity": "color"
          },
          {
            "start": 23,
            "end": 28,
            "value": "shirt",
            "entity": "product"
          },
          {
            "start": 34,
            "end": 41,
            "value": "striped",
            "entity": "pattern"
          },
          {
            "start": 46,
            "end": 55,
            "value": "checkered",
            "entity": "pattern"
          },
          {
            "start": 56,
            "end": 60,
            "value": "blue",
            "entity": "color"
          },
          {
            "start": 61,
            "end": 66,
            "value": "shoe",
            "entity": "product"
          }
        ]
      },
      {
        "text": "i am looking for a red shirt with stripes and checkered blue shoes.",
        "intent": "product_search",
        "entities" : [
          {
            "start": 19,
            "end": 22,
            "value": "red",
            "entity": "color"
          },
          {
            "start": 23,
            "end": 28,
            "value": "shirt",
            "entity": "product"
          },
          {
            "start": 34,
            "end": 41,
            "value": "striped",
            "entity": "pattern"
          },
          {
            "start": 46,
            "end": 55,
            "value": "checkered",
            "entity": "pattern"
          },
          {
            "start": 56,
            "end": 60,
            "value": "blue",
            "entity": "color"
          },
          {
            "start": 61,
            "end": 66,
            "value": "shoe",
            "entity": "product"
          }
        ]
      },
      {
        "text": "i am searching for a green hat with checkers and a striped red socks.",
        "intent": "product_search",
        "entities" : [
          {
            "start": 21,
            "end": 26,
            "value": "green",
            "entity": "color"
          },
          {
            "start": 27,
            "end": 30,
            "value": "hat",
            "entity": "product"
          },
          {
            "start": 36,
            "end": 44,
            "value": "checkered",
            "entity": "pattern"
          },
          {
            "start": 51,
            "end": 58,
            "value": "striped",
            "entity": "pattern"
          },
          {
            "start": 59,
            "end": 62,
            "value": "red",
            "entity": "color"
          },
          {
            "start": 63,
            "end": 68,
            "value": "socks",
            "entity": "product"
          }
        ]
      }
    ]
  }
}
